import part1
import part2

from typing import List, cast


def test_part1():
    test_input = """
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
""".strip().splitlines()
    test_input = cast(List[str], test_input)
    expected_output = 21
    assert part1.solve(test_input) == expected_output


def test_part2():
    test_input = """
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
""".strip().splitlines()
    test_input = cast(List[str], test_input)
    expected_output = 40
    assert part2.solve(test_input) == expected_output


def test_complete_part1():
    with open("input.txt") as f:
        input_data = f.readlines()
    expected_output = 1590
    assert part1.solve(input_data) == expected_output


def test_complete_part2():
    with open("input.txt") as f:
        input_data = f.readlines()
    expected_output = 20571740188555
    assert part2.solve(input_data) == expected_output
